# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
  
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, World!
      - name: Run a multi-line script
        run: echo Other action to build, echo test and deploy your project.
